plex__op_vault: "Applications"
plex__op_key: "Plex"

plex__fileserver: |-
  {{
      lookup(
        'community.general.onepassword',
        plex__op_key,
        vault=plex__op_vault,
        field='fileserver'
      ) | very_mandatory
  }}
plex__domain: |-
  {{
      lookup(
        'community.general.onepassword',
        plex__op_key,
        vault=plex__op_vault,
        field='domain'
      ) | very_mandatory
  }}
plex__cloudflare_api_token: |-
  {{
      lookup(
        'community.general.onepassword',
        plex__op_key,
        vault=plex__op_vault,
        field='cloudflare_api_token'
      ) | very_mandatory
  }}

# Certificate configuration
plex__enable_certbot_hook: true
plex__cert_password: |-
  {%- if plex__enable_certbot_hook | bool -%}
  {{
      lookup(
        'community.general.onepassword',
        plex__op_key,
        vault=plex__op_vault,
        field='cert_password'
      ) | very_mandatory
  }}
  {%- endif -%}
