from typing import Any

from ansible.plugins import AnsiblePlugin

class CacheObject:
    def get(self, key: str, default: Any = None) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...

class BaseInventoryPlugin(AnsiblePlugin):
    inventory: Any
    def add_host(self, host: str, group: str | None = None, port: int | None = None) -> None: ...
    def add_group(self, group: str) -> str: ...
    def add_child(self, group: str, child: str) -> None: ...
    def set_variable(self, host: str, key: str, value: Any) -> None: ...
    def get_groups_dict(self) -> dict[str, list[str]]: ...
    def verify_file(self, path: str) -> bool: ...
    def parse(self, inventory: Any, loader: Any, path: str, cache: bool = True) -> None: ...
    def _read_config_data(self, path: str) -> dict[str, Any]: ...
    def get_option(
        self, option: str, hostvars: dict[str, Any] | None = None, variables: dict[str, Any] | None = None
    ) -> Any: ...

class Constructable:
    inventory: Any
    def _sanitize_group_name(self, name: str) -> str: ...

class Cacheable:
    _cache: CacheObject
    @property
    def cache(self) -> CacheObject: ...
    def get_cache_key(self, path: str) -> str: ...
