from typing import Any

from ansible.plugins import AnsiblePlugin

class BaseInventoryPlugin(AnsiblePlugin):
    inventory: Any
    def add_host(self, host: str, group: str | None = None, port: int | None = None) -> None: ...
    def add_group(self, group: str) -> str: ...
    def add_child(self, group: str, child: str) -> None: ...
    def set_variable(self, host: str, key: str, value: Any) -> None: ...
    def get_groups_dict(self) -> dict[str, list[str]]: ...

class Constructable:
    inventory: Any
    def _sanitize_group_name(self, name: str) -> str: ...
