kopia_client__op_vault: "Applications"
kopia_client__op_key: "{{ inventory_hostname }}"
kopia_client__hostname: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        section="kopia",
        field='hostname'
      ) | very_mandatory
  }}
kopia_client__backup_schedule: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        section="kopia",
        field='schedule'
      ) | very_mandatory
  }}
kopia_client__backup_destination: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        section="kopia",
        field='destination'
      ) | very_mandatory
  }}
kopia_client__username: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        section="kopia",
        field='username'
      ) | very_mandatory
  }}
kopia_client__password: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        section="kopia",
        field='password'
      ) | very_mandatory
  }}
kopia_client__snapshot_command: |-
  {{
      lookup(
        'community.general.onepassword',
        kopia_client__op_key,
        vault=kopia_client__op_vault,
        section="kopia",
        field='snapshot-command'
      ) | very_mandatory
  }}
