apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor/ansible_collection
    contents:
      - path: community.general
        git:
          url: https://github.com/ansible-collections/community.general
          ref: 10.5.0
          depth: 1
      - path: hetzner.cloud
        git:
          url: https://github.com/ansible-collections/hetzner.hcloud
          ref: 4.3.0
          depth: 1
  - path: vendor/ansible_roles
    contents:
      - path: unattended_upgrades
        git:
          url: https://github.com/hifis-net/ansible-collection-toolkit
          ref: v5.3.0
          depth: 1
        includePaths:
          - roles/unattended_upgrades/**/*
        newRootPath: roles/unattended_upgrades
  - path: vendor/pve-nag-buster
    contents:
      - path: .
        git:
          url: https://github.com/foundObjects/pve-nag-buster
          ref: origin/master
          depth: 1
  - path: vendor/exporters
    contents:
      - path: pve_exporter
        git:
          url: https://github.com/prometheus-pve/prometheus-pve-exporter
          ref: v3.5.2
          depth: 1
        includePaths:
          - src/pve_exporter/**/*
        newRootPath: src/pve_exporter
      - path: textfile-collector-scripts
        git:
          url: https://github.com/prometheus-community/node-exporter-textfile-collector-scripts
          ref: origin/master
          depth: 1
        includePaths:
          - zfs*
      - path: pbs-exporter
        # https://github.com/natrontech/pbs-exporter
        githubRelease:
          slug: natrontech/pbs-exporter
          tag: v0.6.6
          # Can't sync checksums with variable release tags...
          disableAutoChecksumValidation: true
          assetNames:
            - "pbs-exporter_v*_linux_amd64.tar.gz"
          unpackArchive:
            path: "pbs-exporter_v0.6.4_linux_amd64.tar.gz"
      - path: kopia-exporter
        # https://github.com/nalabelle/kopia-exporter
        githubRelease:
          slug: nalabelle/kopia-exporter
          tag: v0.3.41
          # I should really add these..
          disableAutoChecksumValidation: true
          assetNames:
            - "kopia-exporter_null_x86_64-unknown-linux-musl.tar.gz"
          unpackArchive:
            path: "kopia-exporter_null_x86_64-unknown-linux-musl.tar.gz"
  - path: .pulumi/bin
    contents:
    # Download pulumi through vendir because nix/devbox versions have problems:
    # Warnings about using plugins from $PATH
    # Can't write import cache files because /nix is immutable
      - path: .
        http:
          url: https://get.pulumi.com/releases/sdk/pulumi-v3.156.0-linux-x64.tar.gz
          sha256: ""
          disableAutoChecksumValidation: true
        unpackArchive:
          path: "pulumi-v3.156.0-linux-x64.tar.gz"
        newRootPath: pulumi
