proxmox__enable_exporters: true
proxmox__enable_pcie: false
proxmox__enable_sanoid: false
proxmox__enable_certbot_hook: true

proxmox__op_vault: "Applications"
proxmox__op_key: "PROXMOX"

proxmox__network_domain: |-
  {{
      lookup(
        'community.general.onepassword',
        'network',
        vault=proxmox__op_vault,
        field='domain'
      )
  }}

proxmox__node_collector_token: |-
  {{
      lookup(
        'community.general.onepassword',
        proxmox__op_key,
        vault=proxmox__op_vault,
        field='node-collector'
      )
  }}

proxmox__cloudflare_api_token: |-
  {{
      lookup(
        'community.general.onepassword',
        'CF_DNS_API_TOKEN',
        vault=proxmox__op_vault,
        field='password'
      )
  }}
