plugin: community.general.proxmox
cache: true
cache_connection: .ansible-cache/proxmox-inventory/
cache_prefix: ""
cache_plugin: community.general.yaml
url: |-
  {{
      lookup(
        'community.general.onepassword',
        'proxmox',
        vault='Applications',
        field='url'
      )
  }}
user: |-
  {{
      lookup(
        'community.general.onepassword',
        'proxmox',
        vault='Applications',
        field='username'
      )
  }}
token_id: |-
  {{
      lookup(
        'community.general.onepassword',
        'proxmox',
        vault='Applications',
        field='token_id'
      )
  }}
token_secret: |-
  {{
      lookup(
        'community.general.onepassword',
        'proxmox',
        vault='Applications',
        field='token_secret'
      )
  }}
keyed_groups:
  - key: proxmox_tags_parsed
    separator: "_"
    prefix: service
want_facts: true
timeout: 30
want_proxmox_nodes_ansible_host: false
