ctrld__op_vault: "Applications"

ctrld__config_file: /etc/controld/ctrld.toml
ctrld__manage_user: true
ctrld__port: 53
ctrld__nextdns_prefix: |-
  {{
      lookup(
        'community.general.onepassword',
        'NextDNS',
        vault=ctrld__op_vault,
        field='prefix'
      ) | very_mandatory
  }}
