# Version management for Renovate
ctrld__version: "1.4.4"

# Control whether to disable the builtin resolver
ctrld__disable_resolver: true

# Installation paths (customizable for UniFi)
ctrld__install_dir: "/usr/local/bin"

# Vault configuration
ctrld__op_vault: "Applications"

# Service configuration
ctrld__config_file: /etc/controld/ctrld.toml
ctrld__manage_user: true
ctrld__port: 53
ctrld__nextdns_prefix: |-
  {{
      lookup(
        'community.general.onepassword',
        'NextDNS',
        vault=ctrld__op_vault,
        field='prefix'
      ) | very_mandatory
  }}
