# Manually join network
# On the first connection, use this
# --auth-key=tskey-auth-...
# For exit nodes
# --advertise-exit-node
# If the host has routes
# --advertise-routes=192.168.210.0/24
# ansible servers -a "tailscale up --accept-dns=false --accept-routes=false"

- name: Set up keyring
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
    keyring: /etc/apt/keyrings/tailscale-archive-keyring.gpg

- name: Set up apt sources
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu noble main"
    filename: tailscale

- name: Install packages
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - tailscale
    state: present

- name: Set up Routing
  when: tailscale_routing
  block:
    - name: Install ethtool
      ansible.builtin.apt:
        name: ethtool
        state: present

    - name: Configure UDP
      ansible.builtin.copy:
        src: etc/networkd-dispatcher/routable.d/50-tailscale
        dest: /etc/networkd-dispatcher/routable.d/50-tailscale
        mode: "0755"
      notify: Restart networkd-dispatcher

    - name: Configure Forwarding
      ansible.builtin.copy:
        src: etc/sysctl.d/99-tailscale.conf
        dest: /etc/sysctl.d/99-tailscale.conf
        mode: "0644"
      notify: Reload sysctl

- name: Configure UFW
  when: tailscale_ufw_config
  block:
    - name: Check if ufw is installed
      shell: command -v ufw
      register: ufw_installed
      changed_when: false
      failed_when: false

    - name: Allow Traffic
      community.general.ufw:
        rule: allow
        proto: any
        interface_in: "tailscale0"
      when: ufw_installed.rc == 0
