# ctrld runs behind dnsmasq on unifi
ctrld__port: 5354
ctrld__nextdns_prefix: |-
  {{
      lookup(
        'community.general.onepassword',
        'NextDNS',
        vault="Applications",
        field='prefix'
      ) | very_mandatory
  }}
