---
- name: Install
  ansible.builtin.include_tasks:
    file: install.yaml
  tags:
    - ctrld_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yaml
  tags:
    - ctrld_configure
