- name: Router
  hosts: unifi
  tags: router
  roles:
    - role: ctrld
      tags: ctrld
    - role: tailscale
      tags: tailscale

- name: Bastion
  hosts: wells
  tags: bastion
  roles:
    - role: basic
      tags: basic
    - role: nextdns
      tags: nextdns
      when: nextdns__enabled | default(false)
    - role: ctrld
      tags: ctrld
      when: ctrld__enabled | default(false)
    - role: wireguard
      tags: wireguard
      when: wireguard__enabled | default(false)
    - role: tailscale
      tags: tailscale
    - role: unattended_upgrades
      tags: unattended-upgrades

## BASIC
- name: Basic Setup
  hosts: proxmox_nodes proxmox_all_qemu proxmox_all_lxc
  roles:
    - role: basic
      tags: basic
- name: Guest Agent
  hosts: proxmox_all_qemu
  tags:
    - guest-agent
  tasks:
    - name: Install guest agent
      ansible.builtin.apt:
        pkg: qemu-guest-agent
        state: present
        update_cache: true
        cache_valid_time: 3600

- name: Compose Hosts
  hosts: service_compose
  roles:
    - role: containers
      tags: containers
    - role: 1password
      tags: 1password
- name: Proxmox
  hosts: proxmox_nodes
  tags: proxmox
  roles:
    - role: proxmox
- name: Unattended Upgrades
  hosts: proxmox_all_qemu proxmox_nodes proxmox_all_lxc
  tags:
    - unattended-upgrades
  roles:
    - role: unattended_upgrades

- name: zfs
  hosts: service_zpool
  tags:
    - zfs
  roles:
    - role: zfs
- name: fileserver
  hosts: service_files
  tags:
    - fileserver
  roles:
    - role: fileserver
## APPS
- name: Syncthing
  hosts: service_files
  tags:
    - syncthing
  roles:
    - role: syncthing
- name: Proxmox Backup Server
  hosts: service_proxmox_backup_server
  tags:
    - proxmox-backup-server
  roles:
    - role: proxmox_backup_server
- name: Plex
  hosts: service_plex
  tags:
    - plex
  roles:
    - role: plex
- name: Kopia Server
  hosts: service_kopia
  tags:
    - kopia-server
    - kopia
  roles:
    - role: kopia_server
- name: Kopia Client
  hosts: proxmox_nodes service_files
  tags:
    - kopia-client
    - kopia
  roles:
    - role: kopia_client
