- name: Include kopia role
  ansible.builtin.include_role:
    name: kopia

- name: Kopia config directory
  ansible.builtin.file:
    path: "{{ kopia_server__home }}/.config/kopia"
    state: "directory"
    mode: "0755"
    owner: backup
    group: backup

- name: Kopia config
  ansible.builtin.template:
    src: _kopia_home/.config/kopia/repository.config.j2
    dest: "{{ kopia_server__home }}/.config/kopia/repository.config"
    mode: "0600"
    owner: backup
    group: backup

- name: Kopia encryption key
  ansible.builtin.template:
    src: _kopia_home/.config/kopia/repository.config.kopia-password.j2
    dest: "{{ kopia_server__home }}/.config/kopia/repository.config.kopia-password"
    mode: "0600"
    owner: backup
    group: backup

- name: Kopia server connection info
  ansible.builtin.blockinfile:
    path: /etc/environment
    block: |
      KOPIA_SERVER_ADDRESS=https://{{ ansible_hostname }}.{{ kopia_server__domain }}:443
      KOPIA_SERVER_USERNAME={{ kopia_server__username }}
      KOPIA_SERVER_PASSWORD={{ kopia_server__password }}
    state: present

- name: Copy kopia services
  ansible.builtin.copy:
    src: systemd/system/
    dest: /etc/systemd/system/
    mode: "0644"
  notify: Reload systemd

- name: Allow user to write to kopia home directory
  ansible.builtin.file:
    path: "{{ kopia_server__home }}"
    state: "directory"
    mode: "02775"
    owner: backup
    group: backup

- name: Copy kopia service templates
  ansible.builtin.template:
    src: "systemd/system/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: "0644"
  loop:
    - kopia-server
  notify: Reload systemd

- name: Copy kopia executables
  ansible.builtin.copy:
    src: usr/local/bin/
    dest: /usr/local/bin/
    mode: "0755"

- name: Copy kopia-sync executable
  ansible.builtin.template:
    src: usr/local/bin/kopia-sync.j2
    dest: /usr/local/bin/kopia-sync
    mode: "0755"

- name: Enable kopia services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - kopia-maintenance.timer
    - kopia-maintenance-full.timer
    - kopia-exporter.path
    - kopia-sync.path
    - kopia-server.service
  notify: Reload systemd

- name: Deploy Let's Encrypt renewal hook for Kopia
  ansible.builtin.template:
    src: etc/letsencrypt/renewal-hooks/deploy/kopia-server.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/kopia-server
    mode: "0755"
  register: renewal_hook_deployed

- name: Create SSL directory for Kopia
  ansible.builtin.file:
    path: "{{ kopia_server__home }}/ssl"
    state: "directory"
    mode: "0750"
    owner: backup
    group: backup

- name: Check if certificate files exist
  ansible.builtin.stat:
    path: "{{ kopia_server__home }}/ssl/fullchain.pem"
  register: cert_file

- name: Run renewal hook to copy certificates
  ansible.builtin.command:
    cmd: /etc/letsencrypt/renewal-hooks/deploy/kopia-server
  environment:
    RENEWED_LINEAGE: "/etc/letsencrypt/live/{{ kopia_server__domain }}"
  when: not cert_file.stat.exists or renewal_hook_deployed is changed
  register: renewal_hook_result
  changed_when: renewal_hook_result.rc == 0
  failed_when: renewal_hook_result.rc != 0

- name: Node collector
  ansible.builtin.include_tasks:
    file: collector.yaml
