- name: Install kopia
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Certbot
  ansible.builtin.include_tasks:
    file: certbot.yaml

- name: Kopia config directory
  ansible.builtin.file:
    path: /var/backups/.config/kopia
    state: "directory"
    mode: "0755"
    owner: backup
    group: backup

- name: Kopia config
  ansible.builtin.template:
    src: var/backups/.config/kopia/repository.config.j2
    dest: /var/backups/.config/kopia/repository.config
    mode: "0600"
    owner: backup
    group: backup

- name: Kopia encryption key
  ansible.builtin.template:
    src: var/backups/.config/kopia/repository.config.kopia-password.j2
    dest: /var/backups/.config/kopia/repository.config.kopia-password
    mode: "0600"
    owner: backup
    group: backup

- name: Kopia server connection info
  ansible.builtin.blockinfile:
    path: /etc/environment
    block: |
      KOPIA_SERVER_ADDRESS=https://{{ ansible_hostname }}.{{ kopia_server__domain }}:443
      KOPIA_SERVER_USERNAME={{ kopia_server__username }}
      KOPIA_SERVER_PASSWORD={{ kopia_server__password }}
    state: present

- name: Copy kopia services
  ansible.builtin.copy:
    src: systemd/system/
    dest: /etc/systemd/system/
    mode: "0644"
  notify: Reload systemd

- name: Allow user to write to /var/backups
  ansible.builtin.file:
    path: /var/backups
    state: "directory"
    mode: "02775"
    owner: backup
    group: backup

- name: Copy kopia service templates
  ansible.builtin.template:
    src: "systemd/system/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: "0644"
  loop:
    - kopia-server
  notify: Reload systemd

- name: Copy kopia executables
  ansible.builtin.copy:
    src: usr/local/bin/
    dest: /usr/local/bin/
    mode: "0755"

- name: Copy kopia-sync executable
  ansible.builtin.template:
    src: usr/local/bin/kopia-sync.j2
    dest: /usr/local/bin/kopia-sync
    mode: "0755"

- name: Enable kopia services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - kopia-maintenance.timer
    - kopia-maintenance-full.timer
    - kopia-exporter.path
    - kopia-sync.path
    - kopia-server.service
  notify: Reload systemd

- name: Node collector
  ansible.builtin.include_tasks:
    file: collector.yaml
