- name: Configure rclone
  ansible.builtin.include_tasks:
    file: rclone.yaml

- name: Install
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Exporter
  ansible.builtin.include_tasks:
    file: exporter.yaml

- name: Ensure renewal hook directory exists
  ansible.builtin.file:
    path: /etc/letsencrypt/renewal-hooks/deploy
    state: directory

- name: Set up cert renewal hooks
  ansible.builtin.copy:
    src: etc/letsencrypt/renewal-hooks/deploy/proxmox-proxy
    dest: /etc/letsencrypt/renewal-hooks/deploy/proxmox-proxy
    mode: "0755"
