- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart networkd-dispatcher
  ansible.builtin.systemd:
    name: networkd-dispatcher
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-tailscale.conf
  changed_when: true
