- name: Install nfs-client
  ansible.builtin.apt:
    pkg: nfs-common
    state: present
    update_cache: true

- name: Create paths for network mounts
  ansible.builtin.file:
    path: "/media/{{ item }}"
    state: directory
    mode: "02775"
  loop:
    - internet
    - movies
    - music
    - television

- name: Create network mounts
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.template', 'etc/fstab.j2') }}"
    path: /etc/fstab
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: true
    prepend_newline: true
  notify:
    - Reload systemctl
    - Remote-fs

- name: Install Plex repo
  deb822_repository:
    name: plex
    types: deb
    uris: https://downloads.plex.tv/repo/deb/
    suites: public
    components: main
    architectures: amd64
    signed_by: https://downloads.plex.tv/plex-keys/PlexSign.key

- name: Install Plex
  ansible.builtin.apt:
    pkg: plexmediaserver
    state: present
    update_cache: true

- name: Install Caddy
  ansible.builtin.include_tasks:
    file: caddy.yaml

- name: Configure Plex certificate management
  when: plex__enable_certbot_hook | bool
  block:
    - name: Ensure letsencrypt hook directory exists
      ansible.builtin.file:
        path: /etc/letsencrypt/renewal-hooks/deploy
        state: directory
        mode: "0755"

    - name: Configure Plex certificate password file
      ansible.builtin.template:
        src: etc/letsencrypt/plex-cert-password.j2
        dest: /etc/letsencrypt/plex-cert-password
        mode: "0600"

    - name: Configure certbot deployment hook for Plex
      ansible.builtin.template:
        src: etc/letsencrypt/renewal-hooks/deploy/plex-cert.j2
        dest: /etc/letsencrypt/renewal-hooks/deploy/plex-cert
        mode: "0755"

    - name: Configure certbot deployment hook for Caddy
      ansible.builtin.template:
        src: etc/letsencrypt/renewal-hooks/deploy/caddy-cert.j2
        dest: /etc/letsencrypt/renewal-hooks/deploy/caddy-cert
        mode: "0755"
      register: caddy_hook_deployed

    - name: Create SSL directory for Caddy
      ansible.builtin.file:
        path: "{{ plex__caddy_home }}/ssl"
        state: "directory"
        mode: "0750"
        owner: caddy
        group: caddy

    - name: Check if certificate files exist for Caddy
      ansible.builtin.stat:
        path: "{{ plex__caddy_home }}/ssl/fullchain.pem"
      register: caddy_cert_file

    - name: Run renewal hook to copy certificates for Caddy
      ansible.builtin.command:
        cmd: /etc/letsencrypt/renewal-hooks/deploy/caddy-cert
      environment:
        RENEWED_LINEAGE: "/etc/letsencrypt/live/{{ plex__domain }}"
      when: not caddy_cert_file.stat.exists or caddy_hook_deployed is changed
      register: caddy_renewal_hook_result
      changed_when: caddy_renewal_hook_result.rc == 0
      failed_when: caddy_renewal_hook_result.rc != 0
