---
# ctrld configuration for UniFi hosts
ctrld__enabled: true
ctrld__install_dir: "/data/controld"
ctrld__config_file: /data/controld/ctrld.toml
# ctrld runs behind dnsmasq on unifi
ctrld__port: 5354
# Don't disable resolver on UniFi devices
ctrld__disable_resolver: false
