---
# ctrld configuration for UniFi hosts
ctrld__enabled: true
ctrld__install_dir: "/data/controld"
ctrld__config_file: /data/controld/ctrld.toml
# ctrld runs behind dnsmasq on unifi
ctrld__port: 5354
# Don't disable resolver on UniFi devices
ctrld__disable_resolver: false

# WireGuard configuration for UniFi hosts
wireguard__enabled: true
wireguard__interface: "wgsrv1"
wireguard__enable_firewall: false
wireguard__enable_config_management: true
wireguard__config_path: "{{ '/data/wireguard/' + wireguard__interface + '.conf' }}"
